controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Redirect common plural path to the French route used in controllers
courses_redirect:
    path: /courses
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /cours
        permanent: false

events_redirect:
    path: /events
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /evenements
        permanent: false
